#!/usr/bin/env bash
set -e
# assert PharoVM with VM profiler and threaded heartbeat

#
# Config variables
#
INSTALLDIR=assert/phcogspur64linuxht
OPT="-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fwrapv -ggdb -O1          -DDEBUGVM=0 -DPharoVM"

. $(dirname $0)/../build/mvm