name: Test

on:
  push:
    branches:
      - 'pharo-*'

  pull_request:
    branches:
      - 'pharo-*'

  workflow_dispatch:


jobs:
  build:
    name: "Build (${{matrix.os}})"
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Add MSYS2 to PATH (Windows only)
        if: matrix.os == 'windows-latest'
        run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        run: ./scripts/ci/github_build.sh